In [279]:
import numpy as np

## NN Dev

In [280]:
class NeuralNetwork:
    def __init__(self, input_size, layer_1_size, layer_2_size, output_size, dtype = np.float64):
        self.input_size = input_size
        self.layer_1_size = layer_1_size
        self.layer_2_size = layer_2_size
        self.output_size = output_size

        self.w1 = np.random.rand(self.input_size, self.layer_1_size).astype(dtype) # np.ones(shape=(self.input_size, self.layer_1_size))
        self.w2 = np.random.rand(self.layer_1_size, self.layer_2_size).astype(dtype) # np.ones(shape=(self.layer_1_size, self.layer_2_size)) 
        self.w3 = np.random.rand(self.layer_2_size, self.output_size).astype(dtype) # np.ones(shape=(self.layer_2_size, self.output_size))
    
    def forward(self, x):
        self.l1 = x @ self.w1
        self.a1 = self.sigmoid(self.l1)
        self.l2 = self.a1 @ self.w2
        self.a2 = self.sigmoid(self.l2)
        self.o = self.a2 @ self.w3
        self.s = self.softmax(self.o)
        return self.s
    
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def softmax(self, x):
        return np.exp(x) / np.sum(np.exp(x))
        


### NN Testing

In [281]:
nn = NeuralNetwork(3, 4, 4, 2)
x = np.array([1, 2, 3]).reshape(1,3)
x

array([[1, 2, 3]])

In [282]:
print(x.shape)
print(nn.w1.shape)
print(nn.w2.shape)
print(nn.w3.shape)

(1, 3)
(3, 4)
(4, 4)
(4, 2)


In [283]:
nn.forward(x)

array([[0.46760209, 0.53239791]])

In [284]:
nn.o

array([[1.29999043, 1.42976391]])

In [285]:
-x

array([[-1, -2, -3]])

In [286]:
np.exp(x)

array([[ 2.71828183,  7.3890561 , 20.08553692]])

In [287]:
1 / (1 + np.exp(-x))

array([[0.73105858, 0.88079708, 0.95257413]])

In [288]:
np.exp(x) / (np.exp(x) + 1)

array([[0.73105858, 0.88079708, 0.95257413]])

In [289]:
np.exp(x)

array([[ 2.71828183,  7.3890561 , 20.08553692]])

In [290]:
np.sum(x)

np.int64(6)

In [291]:
s = np.exp(x) / np.sum(np.exp(x))
s

array([[0.09003057, 0.24472847, 0.66524096]])

In [292]:
np.sum(s)

np.float64(1.0)

## MNIST

### Data Prep

In [293]:
# with open("./train.csv") as f:
#     data = f.readlines()
# data = data[1:]
# data = np.array([[int(x) for x in line.split(",")] for line in data])
# data

In [294]:
def plot_image(image):
    c = 0
    for pixel in image:
        if pixel > 0:
            print("@", end="")
        else:
            print(".", end="")
        print("   ", end="")
        c += 1
        if c == 28:
            print("\n")
            c = 0

In [295]:
X = data[:, 1:]
X.shape

(42000, 784)

In [296]:
X.dtype

dtype('int64')

In [297]:
y = data[:, [0]]
y.shape

(42000, 1)

In [298]:
def one_hot(value, N=10):
    vec = np.zeros(N)
    vec[value] = 1
    return vec

In [299]:
y = np.array([one_hot(c) for c in y])
y.shape

(42000, 10)

### Mnist NN

In [300]:
hidden_dim = 256
mnist_nn = NeuralNetwork(X.shape[1], hidden_dim, hidden_dim, y.shape[1], np.float64)

In [301]:
index = 8
print(y[index])
print(np.where(y[index] == 1)[0][0])
print(mnist_nn.forward(X[index]))
print(np.argmax(mnist_nn.forward(X[index])))
#plot_image(X[index])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
5
[4.31324714e-08 9.49350413e-01 3.84909163e-03 2.60010203e-02
 7.77814852e-06 1.36568743e-03 1.05471434e-03 1.67607207e-02
 1.60904072e-03 1.49087298e-06]
1
